extends: airbnb-base
rules: # see https://eslint.org/docs/rules/
    max-len:
        - warn
        - code: 120
    indent:
        - error
        - 4
        - SwitchCase: 1
          CallExpression:
              arguments: first
    no-multi-spaces:
        - error
        - exceptions:
              VariableDeclarator: true
    no-console: off
    camelcase: off
    strict: off
    key-spacing:
        - error
        - align:
              beforeColon: true
              afterColon: true
              on: colon
    comma-dangle: [error, never]
    arrow-parens: [error, always]
    no-plusplus:
        - error
        - allowForLoopAfterthoughts: true
    no-param-reassign:
        - error
        - props: false
    prefer-destructuring: off
    consistent-return: off # because of Promise callbacks reject() usage
    no-unused-vars:
        - warn
